development:
  adapter: mysql2
  encoding: utf8mb4
  database: iblog_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8mb4
  database: iblog_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8mb4
  database: iblog_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
