# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: developemt

test:
  secret_key_base: test

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d710b1520fa7e49f903b7162739e8ba9a97f31e8e3470458b77fdab64ccc73dd7753534ae6e517e4e75eac0b3049aa75a38f3d7f7bdf1435b2bf1214323fca73
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
